# -*- coding: utf-8 -*-
"""projetoETL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mt_qGBvFS-RYTe2fBnZMLLVJNJ6V2pEq

### Bibliotecas Utilizadas
"""

import pandas as pd
from IPython.display import Image
from google.oauth2 import service_account
from pandas.io import gbq

"""### Extração de Dados"""

contratos = pd.read_csv('/tabela_contratos.csv')

contratos

datas = pd.read_csv('/tabela_datas.csv')
datas

empresas = pd.read_csv('/tabela_empresas.csv')
empresas

"""### Transformação dos Dados"""

contratos_mod = contratos.merge(empresas,
                                 left_on = 'fk_empresa_contratada',
                                 right_on = 'id_empresa',
                                 how = 'left')

contratos_mod

contratos_mod.drop(columns = ['fk_empresa_contratada' , 'id_empresa'], inplace=True)

contratos_mod.head(10)

contratos_final = contratos.merge(datas,
                                 left_on = 'inicio_vigencia',
                                 right_on = 'id_data',
                                 how = 'left')
contratos_final

contratos_final.drop(columns = ['inicio_vigencia' , 'id_data'], inplace=True)

contratos_final.rename(columns = {'data':'data_inicio_vigencia'}, inplace=True)

contratos_final.head(10)

contratos_final_2 = contratos_final.merge(datas,
                                 left_on = 'termino_vigencia',
                                 right_on = 'id_data',
                                 how = 'left')

contratos_final_2.drop(columns = ['termino_vigencia' , 'id_data'], inplace=True)

contratos_final_2.rename(columns = {'data':'data_termino_vigencia'}, inplace=True)

contratos_final_2

contratos_final_2.count()

contratos_final_2.dtypes

contratos_final_2.data_inicio_vigencia = pd.to_datetime(contratos_final_2.data_inicio_vigencia, format = '%d/%m/%Y').dt.date

contratos_final_2.data_termino_vigencia = pd.to_datetime(contratos_final_2.data_termino_vigencia, format = '%d/%m/%Y').dt.date

for i in contratos_final_2.data_termino_vigencia:
    print(i)
    print(pd.to_datetime(i))

contratos_final_2.data_termino_vigencia = contratos_final_2.data_termino_vigencia.str.replace('31/09/2017','30/09/2017')

contratos_final_2.data_termino_vigencia = pd.to_datetime(contratos_final_2.data_termino_vigencia, format = '%d/%m/%Y').dt.date

contratos_final_2.dtypes

contratos_final_2.head(10)

contratos_final_2['tempo_contrato'] = (contratos_final_2.data_termino_vigencia - contratos_final_2.data_inicio_vigencia).dt.days
contratos_final_2

contratos_final_2.nome_contrato.value_counts()

contratos_final_2[contratos_final_2.nome_contrato == '004/16']

contratos_final_2.tempo_contrato.value_counts()

contratos_final_2 = contratos_final_2[contratos_final_2.tempo_contrato > 0]

contratos_final_2.reset_index(drop=True, inplace=True)

"""### Carregamento dos Dados"""

credentials = service_account.Credentials.from_service_account_file(filename='/GBQ.json', scopes=["https://www.googleapis.com/auth/cloud-platform"])

contratos_final_2.to_gbq(credentials=credentials, destination_table='projectetl-401903.datasetETL.etl_csv', if_exists='replace', table_schema=[{'name':'data_inicio_vigencia', 'type':'DATE'},{'name':'data_termino_vigencia', 'type':'DATE'}])